"""
Created on December 29, 2025

This file is subject to the terms and conditions defined in the
file 'LICENSE.txt', which is part of this source code package.

@author: David Moss

signals.report — public API for the report signal package.

All constants and functions are re-exported here so callers using
`import signals.report as report` have uninterrupted access to every name.

See README.md for the full architecture guide.
"""

from signals.report.constants import (
    # Category constants
    CATEGORY_WELLNESS,
    CATEGORY_IT,
    CATEGORY_ENERGY,
    CATEGORY_SAFETY,
    CATEGORY_SECURITY,
    CATEGORY_SOCIAL,
    CATEGORY_HOME,
    CATEGORY_CARE,
    CATEGORY_ALERT,
    CATEGORY_TASK,
    CATEGORY_ACTIVITY,
    # Criticality constants
    CRITICALITY_INFO,
    CRITICALITY_WARNING,
    CRITICALITY_CRITICAL,
    # Sentiment constants
    SENTIMENT_CONCERN,
    SENTIMENT_RESOLUTION,
    SENTIMENT_UPDATE,
    SENTIMENT_CELEBRATION,
    SENTIMENT_SUMMARY,
    # Priority constants
    PRIORITY_CRITICAL,
    PRIORITY_WARNING,
    PRIORITY_INFO,
    # Report address constants
    REPORT_ADDRESS_DAILY,
    REPORT_ADDRESS_WEEKLY,
    REPORT_ADDRESS_MONTHLY,
    PROTECTED_REPORT_ADDRESSES,
    # Event type constants — Sleep
    EVENT_TYPE_SLEEP_WAKEUP,
    EVENT_TYPE_SLEEP_BEDTIME,
    EVENT_TYPE_SLEEP_DURATION,
    EVENT_TYPE_SLEEP_QUALITY,
    EVENT_TYPE_SLEEP_BATHROOM_VISIT,
    EVENT_TYPE_SLEEP_RESTLESSNESS,
    EVENT_TYPE_SLEEP_NAP,
    EVENT_TYPE_SLEEP_OUT_OF_BED,
    EVENT_TYPE_SLEEP_SUMMARY,
    EVENT_TYPE_SLEEP_SCORE,
    # Event type constants — Activity
    EVENT_TYPE_ACTIVITY_MOVEMENT,
    EVENT_TYPE_ACTIVITY_MOBILITY_DAILY,
    EVENT_TYPE_ACTIVITY_BATHROOM_VISIT,
    EVENT_TYPE_ACTIVITY_MEAL,
    EVENT_TYPE_ACTIVITY_MEDICATION_TAKEN,
    EVENT_TYPE_ACTIVITY_MEDICATION_MISSED,
    EVENT_TYPE_ACTIVITY_INACTIVITY,
    EVENT_TYPE_ACTIVITY_EXERCISE,
    EVENT_TYPE_ACTIVITY_SUMMARY,
    # Event type constants — Health
    EVENT_TYPE_HEALTH_FALL,
    EVENT_TYPE_HEALTH_STABILITY_EVENT,
    EVENT_TYPE_HEALTH_HEART_RATE_ALERT,
    EVENT_TYPE_HEALTH_MEDICATION_NON_COMPLIANCE,
    EVENT_TYPE_HEALTH_BLOOD_PRESSURE,
    EVENT_TYPE_HEALTH_BREATHING_RATE,
    EVENT_TYPE_HEALTH_WELLNESS_SCORE,
    EVENT_TYPE_HEALTH_CARE_SCORE,
    EVENT_TYPE_HEALTH_SUMMARY,
    # Event type constants — Stability
    EVENT_TYPE_STABILITY_SCORE,
    EVENT_TYPE_STABILITY_FALL_RISK,
    EVENT_TYPE_STABILITY_COMPONENT_FALLS,
    EVENT_TYPE_STABILITY_COMPONENT_SLEEP,
    EVENT_TYPE_STABILITY_COMPONENT_MOBILITY,
    EVENT_TYPE_STABILITY_COMPONENT_BIOMETRICS,
    EVENT_TYPE_STABILITY_COMPONENT_EVENTS,
    EVENT_TYPE_STABILITY_SUMMARY,
    # Event type constants — Safety
    EVENT_TYPE_SAFETY_WANDERING,
    EVENT_TYPE_SAFETY_UNAUTHORIZED_ACCESS,
    EVENT_TYPE_SAFETY_DEVICE_TAMPERING,
    EVENT_TYPE_SAFETY_DOOR_LEFT_OPEN,
    EVENT_TYPE_SAFETY_WINDOW_LEFT_OPEN,
    EVENT_TYPE_SAFETY_SMOKE_DETECTED,
    EVENT_TYPE_SAFETY_CARBON_MONOXIDE,
    EVENT_TYPE_SAFETY_SUMMARY,
    # Event type constants — Security
    EVENT_TYPE_SECURITY_ALARM_ACTIVATED,
    EVENT_TYPE_SECURITY_BREAK_IN,
    EVENT_TYPE_SECURITY_MOTION_DETECTED,
    EVENT_TYPE_SECURITY_DOOR_UNLOCKED,
    EVENT_TYPE_SECURITY_GARAGE_OPENED,
    EVENT_TYPE_SECURITY_CAMERA_MOTION,
    EVENT_TYPE_SECURITY_SUMMARY,
    # Event type constants — IT
    EVENT_TYPE_IT_DEVICE_OFFLINE,
    EVENT_TYPE_IT_CONNECTIVITY_ISSUE,
    EVENT_TYPE_IT_GATEWAY_PROBLEM,
    EVENT_TYPE_IT_DEVICE_BATTERY_LOW,
    EVENT_TYPE_IT_FIRMWARE_UPDATE,
    EVENT_TYPE_IT_NETWORK_DEGRADED,
    EVENT_TYPE_IT_SUMMARY,
    # Event type constants — Energy
    EVENT_TYPE_ENERGY_HIGH_CONSUMPTION,
    EVENT_TYPE_ENERGY_HVAC_ISSUE,
    EVENT_TYPE_ENERGY_THERMOSTAT_ADJUSTMENT,
    EVENT_TYPE_ENERGY_PEAK_DEMAND,
    EVENT_TYPE_ENERGY_DEVICE_LEFT_ON,
    EVENT_TYPE_ENERGY_SMART_PLUG_OFFLINE,
    EVENT_TYPE_ENERGY_SUMMARY,
    # Event type constants — Social
    EVENT_TYPE_SOCIAL_VISITOR,
    EVENT_TYPE_SOCIAL_TOGETHER,
    EVENT_TYPE_SOCIAL_AWAY,
    EVENT_TYPE_SOCIAL_RETURN,
    EVENT_TYPE_SOCIAL_PHONE_CALL,
    EVENT_TYPE_SOCIAL_MESSAGE_RECEIVED,
    EVENT_TYPE_SOCIAL_SUMMARY,
    # Event type constants — Task
    EVENT_TYPE_TASK_ADDED,
    EVENT_TYPE_TASK_COMPLETED,
    EVENT_TYPE_TASK_OVERDUE,
    EVENT_TYPE_TASK_REMINDER,
    EVENT_TYPE_TASK_SUMMARY,
    # Event type constants — Home
    EVENT_TYPE_HOME_WATER_LEAK,
    EVENT_TYPE_HOME_HVAC_FAILURE,
    EVENT_TYPE_HOME_APPLIANCE_ISSUE,
    EVENT_TYPE_HOME_MAINTENANCE_REQUIRED,
    EVENT_TYPE_HOME_DAYLIGHT_CHANGE,
    EVENT_TYPE_HOME_SUMMARY,
    # Event type constants — Care
    EVENT_TYPE_CARE_CHECK_IN,
    EVENT_TYPE_CARE_REMINDER,
    EVENT_TYPE_CARE_WELLNESS_CHECK,
    EVENT_TYPE_CARE_SUMMARY,
    # Event type constants — Family
    EVENT_TYPE_FAMILY_NOTIFICATION,
    EVENT_TYPE_FAMILY_ALERT,
    EVENT_TYPE_FAMILY_SUMMARY,
    # Event type constants — Alert
    EVENT_TYPE_ALERT_CRITICAL,
    EVENT_TYPE_ALERT_WARNING,
    EVENT_TYPE_ALERT_INFO,
    EVENT_TYPE_ALERT_SUMMARY,
    # Event type constants — Bathroom
    EVENT_TYPE_BATHROOM_VISIT,
    EVENT_TYPE_BATHROOM_DURATION,
    EVENT_TYPE_BATHROOM_FREQUENCY,
    EVENT_TYPE_BATHROOM_SUMMARY,
    # Event type constants — Medication
    EVENT_TYPE_MEDICATION_TAKEN,
    EVENT_TYPE_MEDICATION_MISSED,
    EVENT_TYPE_MEDICATION_REMINDER,
    EVENT_TYPE_MEDICATION_SUMMARY,
    # Event type constants — Meals
    EVENT_TYPE_MEALS_PREPARED,
    EVENT_TYPE_MEALS_CONSUMED,
    EVENT_TYPE_MEALS_SKIPPED,
    EVENT_TYPE_MEALS_SUMMARY,
    # Schema
    EVENT_TYPE_SCHEMA,
)

from signals.report.report import (
    get_event_type_prefix,
    get_schema_for_event_type,
    add_event,
    generate_report,
    delete_report,
    report_generated,
    send_org_report,
)

__all__ = [
    # ---- constants.py ----
    # Category constants
    "CATEGORY_WELLNESS",
    "CATEGORY_IT",
    "CATEGORY_ENERGY",
    "CATEGORY_SAFETY",
    "CATEGORY_SECURITY",
    "CATEGORY_SOCIAL",
    "CATEGORY_HOME",
    "CATEGORY_CARE",
    "CATEGORY_ALERT",
    "CATEGORY_TASK",
    "CATEGORY_ACTIVITY",
    # Criticality constants
    "CRITICALITY_INFO",
    "CRITICALITY_WARNING",
    "CRITICALITY_CRITICAL",
    # Sentiment constants
    "SENTIMENT_CONCERN",
    "SENTIMENT_RESOLUTION",
    "SENTIMENT_UPDATE",
    "SENTIMENT_CELEBRATION",
    "SENTIMENT_SUMMARY",
    # Priority constants
    "PRIORITY_CRITICAL",
    "PRIORITY_WARNING",
    "PRIORITY_INFO",
    # Report address constants
    "REPORT_ADDRESS_DAILY",
    "REPORT_ADDRESS_WEEKLY",
    "REPORT_ADDRESS_MONTHLY",
    "PROTECTED_REPORT_ADDRESSES",
    # Event type constants — Sleep
    "EVENT_TYPE_SLEEP_WAKEUP",
    "EVENT_TYPE_SLEEP_BEDTIME",
    "EVENT_TYPE_SLEEP_DURATION",
    "EVENT_TYPE_SLEEP_QUALITY",
    "EVENT_TYPE_SLEEP_BATHROOM_VISIT",
    "EVENT_TYPE_SLEEP_RESTLESSNESS",
    "EVENT_TYPE_SLEEP_NAP",
    "EVENT_TYPE_SLEEP_OUT_OF_BED",
    "EVENT_TYPE_SLEEP_SUMMARY",
    "EVENT_TYPE_SLEEP_SCORE",
    # Event type constants — Activity
    "EVENT_TYPE_ACTIVITY_MOVEMENT",
    "EVENT_TYPE_ACTIVITY_MOBILITY_DAILY",
    "EVENT_TYPE_ACTIVITY_BATHROOM_VISIT",
    "EVENT_TYPE_ACTIVITY_MEAL",
    "EVENT_TYPE_ACTIVITY_MEDICATION_TAKEN",
    "EVENT_TYPE_ACTIVITY_MEDICATION_MISSED",
    "EVENT_TYPE_ACTIVITY_INACTIVITY",
    "EVENT_TYPE_ACTIVITY_EXERCISE",
    "EVENT_TYPE_ACTIVITY_SUMMARY",
    # Event type constants — Health
    "EVENT_TYPE_HEALTH_FALL",
    "EVENT_TYPE_HEALTH_STABILITY_EVENT",
    "EVENT_TYPE_HEALTH_HEART_RATE_ALERT",
    "EVENT_TYPE_HEALTH_MEDICATION_NON_COMPLIANCE",
    "EVENT_TYPE_HEALTH_BLOOD_PRESSURE",
    "EVENT_TYPE_HEALTH_BREATHING_RATE",
    "EVENT_TYPE_HEALTH_WELLNESS_SCORE",
    "EVENT_TYPE_HEALTH_CARE_SCORE",
    "EVENT_TYPE_HEALTH_SUMMARY",
    # Event type constants — Stability
    "EVENT_TYPE_STABILITY_SCORE",
    "EVENT_TYPE_STABILITY_FALL_RISK",
    "EVENT_TYPE_STABILITY_COMPONENT_FALLS",
    "EVENT_TYPE_STABILITY_COMPONENT_SLEEP",
    "EVENT_TYPE_STABILITY_COMPONENT_MOBILITY",
    "EVENT_TYPE_STABILITY_COMPONENT_BIOMETRICS",
    "EVENT_TYPE_STABILITY_COMPONENT_EVENTS",
    "EVENT_TYPE_STABILITY_SUMMARY",
    # Event type constants — Safety
    "EVENT_TYPE_SAFETY_WANDERING",
    "EVENT_TYPE_SAFETY_UNAUTHORIZED_ACCESS",
    "EVENT_TYPE_SAFETY_DEVICE_TAMPERING",
    "EVENT_TYPE_SAFETY_DOOR_LEFT_OPEN",
    "EVENT_TYPE_SAFETY_WINDOW_LEFT_OPEN",
    "EVENT_TYPE_SAFETY_SMOKE_DETECTED",
    "EVENT_TYPE_SAFETY_CARBON_MONOXIDE",
    "EVENT_TYPE_SAFETY_SUMMARY",
    # Event type constants — Security
    "EVENT_TYPE_SECURITY_ALARM_ACTIVATED",
    "EVENT_TYPE_SECURITY_BREAK_IN",
    "EVENT_TYPE_SECURITY_MOTION_DETECTED",
    "EVENT_TYPE_SECURITY_DOOR_UNLOCKED",
    "EVENT_TYPE_SECURITY_GARAGE_OPENED",
    "EVENT_TYPE_SECURITY_CAMERA_MOTION",
    "EVENT_TYPE_SECURITY_SUMMARY",
    # Event type constants — IT
    "EVENT_TYPE_IT_DEVICE_OFFLINE",
    "EVENT_TYPE_IT_CONNECTIVITY_ISSUE",
    "EVENT_TYPE_IT_GATEWAY_PROBLEM",
    "EVENT_TYPE_IT_DEVICE_BATTERY_LOW",
    "EVENT_TYPE_IT_FIRMWARE_UPDATE",
    "EVENT_TYPE_IT_NETWORK_DEGRADED",
    "EVENT_TYPE_IT_SUMMARY",
    # Event type constants — Energy
    "EVENT_TYPE_ENERGY_HIGH_CONSUMPTION",
    "EVENT_TYPE_ENERGY_HVAC_ISSUE",
    "EVENT_TYPE_ENERGY_THERMOSTAT_ADJUSTMENT",
    "EVENT_TYPE_ENERGY_PEAK_DEMAND",
    "EVENT_TYPE_ENERGY_DEVICE_LEFT_ON",
    "EVENT_TYPE_ENERGY_SMART_PLUG_OFFLINE",
    "EVENT_TYPE_ENERGY_SUMMARY",
    # Event type constants — Social
    "EVENT_TYPE_SOCIAL_VISITOR",
    "EVENT_TYPE_SOCIAL_TOGETHER",
    "EVENT_TYPE_SOCIAL_AWAY",
    "EVENT_TYPE_SOCIAL_RETURN",
    "EVENT_TYPE_SOCIAL_PHONE_CALL",
    "EVENT_TYPE_SOCIAL_MESSAGE_RECEIVED",
    "EVENT_TYPE_SOCIAL_SUMMARY",
    # Event type constants — Task
    "EVENT_TYPE_TASK_ADDED",
    "EVENT_TYPE_TASK_COMPLETED",
    "EVENT_TYPE_TASK_OVERDUE",
    "EVENT_TYPE_TASK_REMINDER",
    "EVENT_TYPE_TASK_SUMMARY",
    # Event type constants — Home
    "EVENT_TYPE_HOME_WATER_LEAK",
    "EVENT_TYPE_HOME_HVAC_FAILURE",
    "EVENT_TYPE_HOME_APPLIANCE_ISSUE",
    "EVENT_TYPE_HOME_MAINTENANCE_REQUIRED",
    "EVENT_TYPE_HOME_DAYLIGHT_CHANGE",
    "EVENT_TYPE_HOME_SUMMARY",
    # Event type constants — Care
    "EVENT_TYPE_CARE_CHECK_IN",
    "EVENT_TYPE_CARE_REMINDER",
    "EVENT_TYPE_CARE_WELLNESS_CHECK",
    "EVENT_TYPE_CARE_SUMMARY",
    # Event type constants — Family
    "EVENT_TYPE_FAMILY_NOTIFICATION",
    "EVENT_TYPE_FAMILY_ALERT",
    "EVENT_TYPE_FAMILY_SUMMARY",
    # Event type constants — Alert
    "EVENT_TYPE_ALERT_CRITICAL",
    "EVENT_TYPE_ALERT_WARNING",
    "EVENT_TYPE_ALERT_INFO",
    "EVENT_TYPE_ALERT_SUMMARY",
    # Event type constants — Bathroom
    "EVENT_TYPE_BATHROOM_VISIT",
    "EVENT_TYPE_BATHROOM_DURATION",
    "EVENT_TYPE_BATHROOM_FREQUENCY",
    "EVENT_TYPE_BATHROOM_SUMMARY",
    # Event type constants — Medication
    "EVENT_TYPE_MEDICATION_TAKEN",
    "EVENT_TYPE_MEDICATION_MISSED",
    "EVENT_TYPE_MEDICATION_REMINDER",
    "EVENT_TYPE_MEDICATION_SUMMARY",
    # Event type constants — Meals
    "EVENT_TYPE_MEALS_PREPARED",
    "EVENT_TYPE_MEALS_CONSUMED",
    "EVENT_TYPE_MEALS_SKIPPED",
    "EVENT_TYPE_MEALS_SUMMARY",
    # Schema
    "EVENT_TYPE_SCHEMA",
    # ---- report.py ----
    "get_event_type_prefix",
    "get_schema_for_event_type",
    "add_event",
    "generate_report",
    "delete_report",
    "report_generated",
    "send_org_report",
]
